# Generated by Django 6.1.1 on 2026-09-28 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['name'], 'verbose_name_plural': 'categorias'},
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['name'], 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['nombre'], 'verbose_name_plural': 'Productos'},
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='email',
            new_name='correo',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='nombre',
            new_name='name',
        ),
    ]
